version: '3.3'

services:
  oak_capture:
    privileged: true
    image: oak_capture:latest
    volumes:
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: /home/nvidia/projects/oakd-research/oak_capture/datasets/
        target: /app/datasets/
      - type: bind
        source: /home/nvidia/.aws/
        target: /.aws/
    environment:
      - DISPLAY=$DISPLAY
      - S3_BUCKET_NAME=oak-data
      - AWS_CONFIG_FILE=/.aws/config
    restart: on-failure
    device_cgroup_rules:
      - 'c 189:* rmw'
