version: '3.3'

services:
  oak_capture:
    privileged: true
    image: oak_capture:latest
    volumes:
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    restart: on-failure
    device_cgroup_rules:
      - 'c 189:* rmw'
